version: '3.8'

services:
  cb-agent-system:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/seanfn/cb-agent-system:latest
    container_name: cb-agent
    stdin_open: true
    tty: true
    env_file:
      - .env.docker

    volumes:
      - ${HOST_REPO_PATH}:/workspace/repo
    command: python -m src.main
    restart: "no"
    network_mode: bridge
